"""Add date column to workouts table

Revision ID: 84e73b10fd49
Revises: fdabf438d9d5
Create Date: 2024-09-10 17:17:11.330800

"""
from alembic import op
import sqlalchemy as sa
from typing import Optional

# revision identifiers, used by Alembic.
revision = '84e73b10fd49'
down_revision = 'fdabf438d9d5'
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
